server:
  port: 8888
  servlet:
    context-path: /cfpt
    application-display-name: cfpt service

spring:
  application:
    name: cfpt-server
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: file:${upload.url}

#上传路径
upload:
  url: /upload/